### ISSUE TITLE
选择图片后crash

### ISSUE THREAD

**Issue by JohnGuSir** [leavesCZY/Matisse#10]
<img width="1706" alt="image" src="https://user-images.githubusercontent.com/75824046/220132243-efdb4fcd-983f-472a-a54d-c3f47704087a.png">

**Comment by leavesCZY** [comment]
@JohnGuSir 看堆栈信息，貌似是由于 Compose 版本不一致导致的。drawText 方法在旧版本里是没有的，Matisse 引用的版本是 compose-bom:2023.01.00，你看下你项目中是否为此版本

**Comment by JohnGuSir** [comment]
@leavesCZY 是的相同的版本
<img width="727" alt="image" src="https://user-images.githubusercontent.com/75824046/220135239-9088f21b-6b4f-4db6-a2fd-7a2cc54e1956.png">

**Comment by leavesCZY** [comment]
@JohnGuSir 能否给我看下你其它 compose 依赖是如何引用的吗？

**Comment by JohnGuSir** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/75824046/220136449-86f69da4-de8a-4ee8-9c7e-32379b32a66a.png">

**Comment by JohnGuSir** [comment]
@leavesCZY  可以看一下你的这个版本是多少吗？
<img width="929" alt="image" src="https://user-images.githubusercontent.com/75824046/220142830-f480f1f6-5e71-47c7-ba91-d994312ea862.png">

**Comment by leavesCZY** [comment]
@JohnGuSir 

正常来说应该是 v1.3.3 版本的

![image](https://user-images.githubusercontent.com/30774063/220143741-a1054844-6b29-43cd-a562-13b6c1817382.png)

官网也可以查找对应版本

https://developer.android.com/jetpack/compose/bom/bom-mapping?hl=zh_cn

**Comment by JohnGuSir** [comment]
是我使用的accompanist 版本太高了。

**Comment by JohnGuSir** [comment]
感谢

**Comment by JokinYang** [comment]
> 是我使用的accompanist 版本太高了。

你好，我也遇到了accompanist版本太高导致的bug。可以麻烦问一下和当前Matisse兼容的accompanist的版本号是多少呢？
