### ISSUE TITLE
MatisseContract  能否增加一个直接进入拍照的功能？

### ISSUE THREAD

**Issue by Zhao-YinGang** [leavesCZY/Matisse#12]
当前需要进入相册之后再点相机才能打开相机拍照，无法直接进行拍照，建议给MatisseContract  增加一个直接进入拍照的选项

**Comment by leavesCZY** [comment]
@Zhao-YinGang 我倒是没想过会有仅用 Matisse 来拍照的场景，我后续安排个版本加上这个功能

**Comment by leavesCZY** [comment]
@Zhao-YinGang 我新增了一个 MatisseCaptureContract，支持直接启动拍照流程，应该能满足你的需求了

**Comment by Zhao-YinGang** [comment]
thanks : )
