### ISSUE TITLE
java.lang.AbstractMethodError: abstract method "void github.leavesczy.matisse.ImageEngine.Image"

### ISSUE THREAD

**Issue by kgduyygyfhvk** [leavesCZY/Matisse#19]
说我没有实现，可是我已经按照方法写了

**Comment by leavesCZY** [comment]
@kgduyygyfhvk 你这代码看起来大小写都不太对：@parcelize @composable，确定项目中写对了吗。另外也检查下是否真的引入了 Parcelize 插件

**Comment by kgduyygyfhvk** [comment]
![image](https://github.com/leavesCZY/Matisse/assets/51815201/26070793-0de3-46a6-a489-f4a787d015db)

**Comment by kgduyygyfhvk** [comment]
![image](https://github.com/leavesCZY/Matisse/assets/51815201/33ed1686-76ab-4356-bac5-fdaf3fcf5318)
这里报错了，不知道啥情况

**Comment by kgduyygyfhvk** [comment]
![image](https://github.com/leavesCZY/Matisse/assets/51815201/2d4ca37e-fa8b-43c1-a145-3ea228b55fb1)

**Comment by leavesCZY** [comment]
会不会是因为你没有设置 kotlinCompilerExtensionVersion 的原因，compose 是需要这个才可以的，具体的版本号取决你项目的 kotlin 版本

```kotlin
    composeOptions {
        kotlinCompilerExtensionVersion "1.4.4"
    }
```

**Comment by kgduyygyfhvk** [comment]
@leavesCZY 但是我并没有用compose

**Comment by kgduyygyfhvk** [comment]
![image](https://github.com/leavesCZY/Matisse/assets/51815201/dd1561d9-aec5-446c-9901-eae8c11cf6e1)

**Comment by leavesCZY** [comment]
一样的，只要你引入了 Matisse，就相当于在用 compose 呀，一样要引入 kotlinCompiler

**Comment by kgduyygyfhvk** [comment]
![image](https://github.com/leavesCZY/Matisse/assets/51815201/d102161a-36e7-4e8f-985f-cebceca14e7e)
解决了，是要用compose才行，还要加这句compose true

**Comment by leavesCZY** [comment]
你这也提醒到我了，我在 wiki 里补充说明了这种情况了
