### ISSUE TITLE
一点小建议：图片缩放 & 加载状态

### ISSUE THREAD

**Issue by FunnySaltyFish** [leavesCZY/Matisse#22]
- 逛 Github 的时候发现了个库：[https://github.com/saket/telephoto](https://github.com/saket/telephoto)，是专门用于支持图片的缩放的，或许可以参考？
- 进入图片选择页面时要不加一个简单的 Loading？我的真机有大约 7k 张图片，进入到页面后就只有左上角的“拍照” item，要等待十几秒才能加载出图片，这期间的等待没有 UI 或者 提示文本。加一点简单的 Loading UI 似乎更好？

**Comment by leavesCZY** [comment]
感谢建议

- 现在 Matisse 是通过 ImageEngine 将加载图片的逻辑交由引用方来实现，如果可以的话，我也比较想让引用方自己来决定是否要引入 telephoto，按需集成。但现在 telephoto 和 Matisse 之间会存在一些手势冲突，后续我思考下应该怎么做比较好
- 我倒是没有想过图片很多的情况，的确有道理，我后续补上

再次感觉建议哈

**Comment by leavesCZY** [comment]
@FunnySaltyFish 感谢建议

- 现在 Matisse 是通过 ImageEngine 将加载图片的逻辑交由引用方来实现。比较理想的情况，是让引用方也自己来决定是否要引入 telephoto，按需集成。我试了下，现在 telephoto 和 Matisse 之间会存在一些手势冲突，完全交由外部来集成的话又很受限。后续我思考下应该怎么做比较好
- 我倒是没有想过图片很多的情况，的确有道理，我在 1.0.0-beta03 版本里面补上了

**Comment by panpf** [comment]
各位大佬，我开发的支持 compose 的图片缩放组件 ZoomImage （ https://github.com/panpf/zoomimage ）进入 beta 公开测试阶段了，[README](https://github.com/panpf/zoomimage/releases) 页面有详细的介绍和文档以及和其它优秀图片缩放库的对比，欢迎到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果。
