### ISSUE TITLE
Java项目可以用吗

### ISSUE THREAD

**Issue by xueqi-pki** [leavesCZY/Matisse#29]
我们现在的项目是一个老的，全部用Java开发的项目，并且目前没有使用kotlin的想法。这样的话可否使用您的这个项目呢？

**Comment by leavesCZY** [comment]
@xueqi-pki 这样的话不行噢，现在由于有 ImageEngine，所以主项目也必须用到 Kotlin 才行。但即使没有 ImageEngine，引入 Matisse 也相当于引入了 Kotlin，所以我觉得不管咋样你都是要用到 Kotlin 的
