### ISSUE TITLE
类文件具有错误的版本 61.0, 应为 55.0

### ISSUE THREAD

**Issue by luhenchang** [leavesCZY/Matisse#30]
作者辛苦了。compose中用起来很方便。
在依赖了 kapt("androidx.room:room-compiler:2.5.1")之后，编译过程会失败。具体问题如下：
`
/Users/wangfeiwangfei/wangfei/xtd_program/Design/app/build/tmp/kapt3/stubs/debug/com/example/design/widget/engine/CoilImageEngine.java:9: 错误: 无法访问ImageEngine
public final class CoilImageEngine implements github.leavesczy.matisse.ImageEngine {
                                                                      ^
  错误的类文件: /Users/wangfeiwangfei/.gradle/caches/transforms-3/bb316340c778c9fffa4ee71787e8cb2d/transformed/jetified-Matisse-1.0.1-api.jar(/github/leavesczy/matisse/ImageEngine.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
/Users/wangfeiwangfei/wangfei/xtd_program/Design/app/build/tmp/kapt3/stubs/debug/com/example/design/widget/engine/CoilImageEngine.java:19: 错误: 无法访问MediaResource
    github.leavesczy.matisse.MediaResource mediaResource, @org.jetbrains.annotations.NotNull()
                            ^
  错误的类文件: /Users/wangfeiwangfei/.gradle/caches/transforms-3/bb316340c778c9fffa4ee71787e8cb2d/transformed/jetified-Matisse-1.0.1-api.jar(/github/leavesczy/matisse/MediaResource.class)
    类文件具有错误的版本 61.0, 应为 55.0
    请删除该文件或确保该文件位于正确的类路径子目录中。
`

**Comment by leavesCZY** [comment]
你好，这个问题看起来有可能是因为 Matisse 的 sourceCompatibility、targetCompatibility、jvmTarget 等指向的是 Java 17，而你的项目是用的 Java 11，两者冲突导致的，但我没能复现出你这个问题，你尝试下将上述配置和 AS 的 Gradle JDK 改成 Java 17，看看是否能编译通过

**Comment by luhenchang** [comment]
问题正如你说所，感谢业志成大佬，掘金文章写的都太棒了。一直看你的文章。

**Comment by leavesCZY** [comment]
@luhenchang 解决了就好。我在掘金也关注了你 😂 要达到你的水平我的路还很长

**Comment by luhenchang** [comment]
大佬别这样，我是读你文章长大的。
