### ISSUE TITLE
貌似没有传递已经选择照片的参数

### ISSUE THREAD

**Issue by zhaofawu** [leavesCZY/Matisse#31]
比如第一次选择了两张照片，再次选择的时候，默认这两个照片已经勾选

**Comment by leavesCZY** [comment]
@zhaofawu 是的，目前暂无此选项，外部可以先通过判断 Uri 来过滤掉相同图片

**Comment by leavesCZY** [comment]
@zhaofawu  

可以使用此 dev 版本来使用这个功能：com.github.leavesCZY:Matisse:bc69c4640c

新增了一个 MediaFilter 参数来对媒体资源进行过滤并且提供默认选中的功能。但此功能还处于开发阶段，不保证和后续版本一定兼容，你可以先尝试着用

**Comment by zhaofawu** [comment]
@leavesCZY 
好的，非常感谢
