### ISSUE TITLE
大佬能写个kotlin 接入指南吗？

### ISSUE THREAD

**Issue by guangxingZhao** [leavesCZY/Matisse#32]
项目里面都是Compose 小白很难受啊

**Comment by leavesCZY** [comment]
@guangxingZhao wiki 里有写到纯 View 体系的呀，也就 ImageEngine 这一节需要一点 compose 知识而已

![](https://github.com/leavesCZY/Matisse/assets/30774063/79f59781-383f-471c-9188-ec0ed6cd4228)

**Comment by guangxingZhao** [comment]
好的感谢，找到了 指南层级比较深，默认未展开，大佬可以考虑放在这个页面？[
<img width="758" alt="image" src="https://github.com/leavesCZY/Matisse/assets/25795179/66d2c4c1-ef36-4a95-9b4c-c34465b2cb51">
](url)
