### ISSUE TITLE
uri Failed to load resource

### ISSUE THREAD

**Issue by pinglu0096** [leavesCZY/Matisse#34]
/使用Gilde錯誤訊息如下
Glide: Load failed for [MediaResource(id=1000000500, bucketId=540528482, bucketName=Download, uri=content://media/external/file/1000000500, path=/storage/emulated/0/Download/下載 (10).jpeg, name=下載 (10).jpeg, mimeType=image/jpeg)] with dimensions [1080x2134]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource

使用 Matisse 取得無法顯示的uri
content://media/external/file/1000000500

使用([PickMultipleVisualMedia](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickMultipleVisualMedia?hl=zh-tw))方式取得可正常顯示的 uri 範例如下
content://media/picker/0/com.android.providers.media.photopicker/media/1000000500

是否有解決的方式呢？謝謝

**Comment by leavesCZY** [comment]
你怎么开了又关呢。用 Coil 是否能正常加载呢？如果可以的话说明 Uri 没问题，那就可能是 Glide 配置的问题了

**Comment by pinglu0096** [comment]
後來發現是可以成功加載的，是Glide配置發生問題，謝謝開發好用的套件！

**Comment by leavesCZY** [comment]
没问题就好哈
