### ISSUE TITLE
compose 版图片缩放组件 ZoomImage 推荐

### ISSUE THREAD

**Issue by panpf** [leavesCZY/Matisse#35]
大佬你好，看到你的图片选择库项目很优秀，就是示例 App 中还没有图片缩放功能，正好我开发的 compose 版图片缩放组件 ZoomImage 刚刚发布了 beta 版本，可以公开测试了 ，欢迎体验并反馈意见，也可以到 [release](https://github.com/panpf/zoomimage/releases) 页面下载 APK 体验效果。

https://github.com/panpf/zoomimage

**Comment by leavesCZY** [comment]
写得很棒👍👍👍Matisse 的确需要一个 Compose 版本的图片缩放功能，目前 Matisse 显示 Image 的逻辑是由引用方实现的，有需要集成图片缩放功能的同学可以自行引入

**Comment by panpf** [comment]
多谢大佬肯定，直接在 Matisse 库中集成肯定不合适，在 sample app 中使用一下，完善一下 sample app 的功能就可以了。

**Comment by leavesCZY** [comment]
好嘞，我尝试看看是否能兼容

**Comment by leavesCZY** [comment]
@panpf 你好，我在集成 zoomimage 的过程中发现了一个问题。Matisse 的图片预览页面是包裹在 HorizontalPager 内的，我将每个 Page 的图片交由 zoomimage 显示。当我尝试连续多次左右滑动切换图片时，就会出现图片无法缩放的情况了，CoilZoomAsyncImage 和 GlideZoomAsyncImage 都有这个问题。我运行了下 zoomimage 中的 sample，发现也存在这个情况

**Comment by panpf** [comment]
问题已经稳定复现，很好解决，一会儿要赶高铁，容我晚上到了地方解决一下，再发个版本

**Comment by panpf** [comment]
正在上传新版本，预计半小时后你就能看到新版本了 beta02

**Comment by panpf** [comment]
beta02 可以用了

**Comment by leavesCZY** [comment]
ok，我已经引入到 Matisse 的 demo 里了，后续 Matisse 发布下个版本时，我补充下图片缩放功能的情况
