### ISSUE TITLE
适配 Android 14 Selected Photos Access

### ISSUE THREAD

**Issue by imndx** [leavesCZY/Matisse#36]
如下图所示，点击`Select photos and videos`时，弹出的是 Android 新增的 `PhotoPicker`界面，选取一些图片之后，选中的图片，才会出现在项目的图片选择界面。

并且，之后不再弹出授权界面，导致后续只能选取第一次从`PhotoPicker`选取的照片。

<img width="282" alt="image" src="https://github.com/leavesCZY/Matisse/assets/34434072/ecb41022-6ec8-4e68-94c5-2608f84b9607">

**Comment by leavesCZY** [comment]
按我的理解，如果用户只授予了查看部分图片的权限的话，那这种情况不就很正常了吗？你觉得 Matisse 能够如何进行适配呢？

**Comment by leavesCZY** [comment]
按我的理解，如果用户只授予了查看部分图片的权限的话，那这种情况不就很正常了吗？你是希望 Matisse 实现什么适配效果呢？另外，在 Android 13 及以上的系统版本上，我推荐直接使用系统内置的图片选择器来选择图片

**Comment by imndx** [comment]
其实是一个交互问题


1. 进入本项目的图片选择界面，弹出授权界面
2. 点击上图中的`Select photos and videos`，弹出弹出系统的`PhotoPicker`，然后在里面选择允许当前 app 访问的图片并确定
3. 本项目的图片选择界面这时候会展示上一步选中的图片，用户此时可选取本次想选取的图片

问题出在第 2 步，用户选了一批图片之后，后续通过本项目选取图片时，不会弹授权界面了，只能选取第 2 步选中的那批，不能选新的图片。

**Comment by leavesCZY** [comment]
@imndx 我理解你说的这种情况。你应该是希望 Matisse  能够读取到设备内的所有媒体资源，而非仅是部分媒体资源？因为用户点击权限弹窗中的哪个选项我们是无法控制的，而 “Select photos and videos” 这个选项对于 App 来说也相当于是授予了权限，所以我想不出来 Matisse 能够有啥手段来实现你想要的效果，个人感觉是没有办法的。（我对 Android 14 的适配还没仔细验证，以上属于我的个人见解，有不对的地方欢迎指正）

**Comment by imndx** [comment]
谢谢你的答复，我再研究研究 Android 14 的适配问题，如果有什么新发现，我会继续附到这个 issue 下面

**Comment by leavesCZY** [comment]
@imndx 你好，我验证了下，发现 Android 14 的设备如果想要实现上诉效果的话，是需要依赖于 READ_MEDIA_VISUAL_USER_SELECTED 这个新增的权限的。只是这样也还会有其它问题：当用户选中的是 “Select photos and videos”  时，每次打开 Matisse 时都需要先弹出系统级别的媒体选择弹窗，用户选择允许 App 读取的媒体资源后，Matisse 才能读取到这部分资源，整个流程就很奇怪。所以我还是建议在 Android 13 及以上的系统版本上直接使用系统内置的图片选择器比较好

**Comment by imndx** [comment]
好的，谢谢，先观望看看大家都是怎么适配`Android 14`的。
