### ISSUE TITLE
implementation("com.github.leavesCZY:Matisse:1.0.4")更新不下来

### ISSUE THREAD

**Issue by iLucasLiu** [leavesCZY/Matisse#37]
已经增加
maven { url 'https://jitpack.io' }
mavenCentral()

其他github都可以更新下来的。

**Comment by leavesCZY** [comment]
如果确定引用方式没问题的话，你可以试着调整下几个maven地址的先后顺序，看看能不能下载到

**Comment by iLucasLiu** [comment]
> 如果确定引用方式没问题的话，你可以试着调整下几个maven地址的先后顺序，看看能不能下载到

试过了，还是更新不了。或者在哪能下arr或jar，我直接引用呢，您那有么？

**Comment by leavesCZY** [comment]
没有这些噢。建议你还是先在这个网址上先检查下各种配置项是否正确： https://jitpack.io/#leavesCZY/Matisse

**Comment by iLucasLiu** [comment]
我看您的构建使用的gradle.kt构建的，我这还是以前的.gradle构建的。需要加什么特殊配置么？
我刚到家让室友试了下，也更新不下来。

**Comment by leavesCZY** [comment]
源代码的构建方式并不影响你的引用方式。gradle 有的版本差异较大，声明maven地址的方式回头点差别，你把你声明jitpack和引用依赖的地方截下图，我看是否有问题

**Comment by iLucasLiu** [comment]
> 源代码的构建方式并不影响你的引用方式。gradle 有的版本差异较大，声明maven地址的方式回头点差别，你把你声明jitpack和引用依赖的地方截下图，我看是否有问题

<img width="928" alt="截屏2023-10-13 09 36 48" src="https://github.com/leavesCZY/Matisse/assets/3734375/71623ff6-d902-4c19-9831-02bf75c994ae">
<img width="750" alt="截屏2023-10-13 09 38 20" src="https://github.com/leavesCZY/Matisse/assets/3734375/b8097967-dcc6-4c92-890f-7606571dd54f">

<img width="762" alt="截屏2023-10-13 09 38 05" src="https://github.com/leavesCZY/Matisse/assets/3734375/a3bff2fb-3ed4-4cc1-acd9-399495b179da">

**Comment by leavesCZY** [comment]
拉取依赖失败时的报错信息是不是都指向了阿里云？有点怀疑在拉取 matisse 时，你的项目只从阿里云仓库里拉，没有尝试从 jitpack 源获取

**Comment by iLucasLiu** [comment]
> 拉取依赖失败时的报错信息是不是都指向了阿里云？有点怀疑在拉取 matisse 时，你的项目只从阿里云仓库里拉，没有尝试从 jitpack 源获取



> 拉取依赖失败时的报错信息是不是都指向了阿里云？有点怀疑在拉取 matisse 时，你的项目只从阿里云仓库里拉，没有尝试从 jitpack 源获取

调整过顺序，把maven { url 'https://jitpack.io' }放首位也还是不行。您那边使用正常非kt的gradle构建可以更新下来么？

**Comment by leavesCZY** [comment]
我确定我这边是可以的。你可以切换为以下方式再试试看，如果还不行的，只能说是你的网络问题了
![](https://github.com/leavesCZY/Matisse/assets/30774063/2d55c072-d1ae-4608-ad68-d70056565879)

**Comment by iLucasLiu** [comment]
> 我确定我这边是可以的。你可以切换为以下方式再试试看，如果还不行的，只能说是你的网络问题了 ![](https://user-images.githubusercontent.com/30774063/274776169-2d55c072-d1ae-4608-ad68-d70056565879.png)

我擦，就差一个google()，就可以更新下来了。

**Comment by leavesCZY** [comment]
哈哈哈，看来是阿里云的 Google 源有点问题，导致其它关联依赖你一直拉取不到
