### ISSUE TITLE
框架是否有展示图片的接口？

### ISSUE THREAD

**Issue by iLucasLiu** [leavesCZY/Matisse#38]
我选择完图片后展示在我们自己的列表里。然后点击列表里这张图片在单独放大展示出来，咱们有直接传递uri或path展示图片的接口么？

**Comment by leavesCZY** [comment]
没有噢。Matisse 是一个本地图片选择框架，我不会给它集成任何多余的功能的

**Comment by iLucasLiu** [comment]
其实就是选择完预览的那个页面，是否有对外的接口嘞。

**Comment by leavesCZY** [comment]
我知道你的意思，没有开放给外部使用，也不应该开放
