### ISSUE TITLE
在写GlideImageEngine的实现时，发现和下载的demo中ImageEngine的方法参数有点差别。

### ISSUE THREAD

**Issue by iLucasLiu** [leavesCZY/Matisse#39]
如题，我用最新的1.0.4版本。demo源码中Thumbnail和Image方法的参数只有一个；我工程里的那两个方法有三个参数。如下图。

<img width="645" alt="截屏2023-10-13 14 59 45" src="https://github.com/leavesCZY/Matisse/assets/3734375/cd006173-380f-4bfc-94a9-db86b09d2499">
<img width="620" alt="截屏2023-10-13 14 59 52" src="https://github.com/leavesCZY/Matisse/assets/3734375/97790471-f268-4fee-a337-37d39c991ec6">

**Comment by leavesCZY** [comment]
1.0.4 版本是当前对外发布的最新 release 版本，你看的源码属于下一个 release 版本的内容，此版本我对 ImageEngine 进行了大改，所以会有上诉差别

**Comment by leavesCZY** [comment]
每发布一个 release 版本，我都会打一个 tag，你可以根据 tag 来知道哪个版本对应哪次 commit。当前最新一次 commit 对应的远程依赖是：com.github.leavesCZY:Matisse:90f7e3ade0，你选择 1.0.4 或者这个版本均可以
![image](https://github.com/leavesCZY/Matisse/assets/30774063/bbceb384-962e-4e08-a120-45483261f4eb)

**Comment by iLucasLiu** [comment]
这样子啊， 明白了，那我也把你demo中的GlideImageEngine稍微改造下使用啦。
