### ISSUE TITLE
我引用下面的版本没有ZoomableGlideImage类，你的demo中引用同样的版本就有这个类。

### ISSUE THREAD

**Issue by iLucasLiu** [leavesCZY/Matisse#40]
implementation("me.saket.telephoto:zoomable-image-glide:${zoomableImageVersion}")
val zoomableImageVersion = "0.6.2"

我引用完只有ZoomableImage，但没有ZoomableGlideImage。

**Comment by leavesCZY** [comment]
你没找到而已吧……

**Comment by iLucasLiu** [comment]
> 你没找到而已吧……

me.saket.telephoto.zoomable.glide.ZoomableGlideImage从glide开始就找不到这个包了。
com.github.panpf.zoomimage.GlideZoomAsyncImage 也是类似找不到。

引入的是下面这两个
implementation "me.saket.telephoto:zoomable-image-glide:0.6.2"
implementation "io.github.panpf.zoomimage:zoomimage-compose-glide:1.0.0-beta03"

<img width="773" alt="截屏2023-10-13 16 50 27" src="https://github.com/leavesCZY/Matisse/assets/3734375/b743f5d2-0fe7-44f0-9a40-7dd548dc55d6">
<img width="724" alt="截屏2023-10-13 16 52 31" src="https://github.com/leavesCZY/Matisse/assets/3734375/970aa23c-2475-401b-91d3-532058582b16">

**Comment by leavesCZY** [comment]
那就是你没拉到依赖吧。另外，那些只是我为 Matisse 提供的一些示例代码而已，并不包含在 Matisse 的源代码内，你这些问题已经超出 Matisse 的范畴了
