### ISSUE TITLE
有考虑支持视频预览的播放吗，或者开放一个接口出来

### ISSUE THREAD

**Issue by fenglintianxia6** [leavesCZY/Matisse#42]
现在视频的预览跳转到第三方的app,感觉这个离开主体app的操作不太友好

**Comment by leavesCZY** [comment]
开放一个接口出来倒是不难，主要是我觉得开放出来意义不大，预览操作搞得太复杂感觉没有必要

**Comment by fenglintianxia6** [comment]
> 开放一个接口出来倒是不难，主要是我觉得开放出来意义不大，预览操作搞得太复杂感觉没有必要

感觉跳转第三方的app，这个操作脱离了主体app，产品和领导都不太能接受。

另外还有个小问题也给大佬反馈一下。
我携带着已经选择好的图片跳转过去，然后使用拍照的话，返回的结果里面，目前看貌似只返回了拍照的照片，之前选择的照片的uri在结果里是没有携带的。

**Comment by leavesCZY** [comment]
是这样没错，因为用户想要的效果是不确定的，不确定用户是只想返回拍照结果，还是说想要全都返回。或者说我可以改成当 maxSelectable 为 1 时就只返回拍照结果，maxSelectable 大于1时就都全部返回

**Comment by leavesCZY** [comment]
补充下，目前的 1.1.4 版本针对拍照操作已做出了调整
