### ISSUE TITLE
1.1.0 在华为平板上面拍照之后点击确认无法拿到数据。不清楚是设置问题还是代码问题。手机端正常，华为平板出现此问题。

### ISSUE THREAD

**Issue by luhenchang** [leavesCZY/Matisse#43]
![picture01](https://github.com/leavesCZY/Matisse/assets/25732875/d73cdcf1-8a9f-4758-a481-9f9fef07144e)
![picture02](https://github.com/leavesCZY/Matisse/assets/25732875/38c490ce-4ec3-4fd6-bead-eb63e6966b6e)

**Comment by luhenchang** [comment]
我自己看看是不是配置什么的问题。我运行大佬您的demo似乎正常运行。

**Comment by luhenchang** [comment]
1.1.0 的缺发现此问题。没有具体的更debug，升级到了1.1.2正常。

**Comment by leavesCZY** [comment]
那我也是有点迷糊了，1.1.2 版本我刚好主要也是改动了拍照逻辑，难道是我无意中修复了之前就存在的某个bug吗。。但看到你说手机端是正常的就更加迷糊了
