### ISSUE TITLE
请问选择图片的activity只能竖屏吗？我看好像是写死的

### ISSUE THREAD

**Issue by xuexixuexijpg** [leavesCZY/Matisse#44]
如题

**Comment by leavesCZY** [comment]
内部的确有声明了屏幕方向，但也不算写死，外部想要自定义的话其实可以像以下这样覆盖掉 screenOrientation 属性

![image](https://github.com/leavesCZY/Matisse/assets/30774063/6d42a8cb-b26c-452f-98a4-a3b45f915bee)

**Comment by xuexixuexijpg** [comment]
> 内部的确有声明了屏幕方向，但也不算写死，外部想要自定义的话其实可以像以下这样覆盖掉 screenOrientation 属性
> 
> ![image](https://user-images.githubusercontent.com/30774063/282820386-6d42a8cb-b26c-452f-98a4-a3b45f915bee.png)

好的，感谢
