### ISSUE TITLE
相册模式下，图片或视频二选一

### ISSUE THREAD

**Issue by weinierfei** [leavesCZY/Matisse#45]
大佬好，请问如果我要试下相册模式下图片、视频二选一，支持不？就是选择了视频，就不能选图片，反之一样。

**Comment by leavesCZY** [comment]
目前没有这个功能哦，建议还是直接先让用户明确是想选择视频还是图片后再跳转到 Matisse

**Comment by weinierfei** [comment]
感谢大佬回复，这个是产品需求，产品就要这样，咱没办法。其实还是模仿之前的微信做的，之前的微信就是选择视频后，其他图片不可选中（置灰）。

**Comment by leavesCZY** [comment]
能理解你的需求场景，但就是你想要现在立即有这功能的话不太现实哦，或者说你可以 fork 了项目自己改动下

**Comment by weinierfei** [comment]
好的呢，感谢大佬回复。

**Comment by leavesCZY** [comment]
补充下，目前的 1.1.4 版本已支持此功能
