### ISSUE TITLE
你好这个库支持设置读取照片的缩率图uri吗？

### ISSUE THREAD

**Issue by kennysqwa** [leavesCZY/Matisse#47]
如果手机照片比较多。每次打开要等6 7秒才显示照片。或者可以设置缓存吗？

**Comment by leavesCZY** [comment]
目前没有读取缩略图的方法。会加载比较久应该也和显示的是不是缩略图没有大的关系，主要是因为图片太多的话读取相册列表就会比较久。另外，debug 包和 release 包的性能差异是比较大的，在 release 包下也需要这么久吗

**Comment by kennysqwa** [comment]
感谢回复。我回头试一下release 包。
