### ISSUE TITLE
关于自定义媒体列表页顶部和底部View的配置

### ISSUE THREAD

**Issue by fanyafeng** [leavesCZY/Matisse#48]
能不能将上下的view的修改做一个配置，暂时不想直接拷贝源码自己再去修改view，例如：
![img_v3_028s_d84ee1ae-d924-425b-ad6c-d6f97979d62g](https://github.com/leavesCZY/Matisse/assets/25732455/aec58a0d-6512-4d8a-a4d9-3104e24a4d69)
![img_v3_028s_46bfbe0a-c8df-45d9-8cf4-6e873127c0fg](https://github.com/leavesCZY/Matisse/assets/25732455/f34fb514-bb40-49dc-b074-1a2c424898be)

**Comment by leavesCZY** [comment]
这种不太现实噢，不考虑这种方式

**Comment by fanyafeng** [comment]
哦哦，好吧，那只能改源代码了，不过这样就得手动同步你的更新了

发件人: leavesCZY ***@***.***>
日期: 星期一, 2024年3月11日 17:57
收件人: leavesCZY/Matisse ***@***.***>
抄送: 樊亚风 ***@***.***>, Author ***@***.***>
主题: Re: [leavesCZY/Matisse] 关于自定义媒体列表页顶部和底部View的配置 (Issue #48)

这种不太现实噢，不考虑这种方式

―

**Comment by leavesCZY** [comment]
是的。毕竟需要自定义 UI 的属于小众需求，只开放一部分的话意义不大，开放全部又不太现实

**Comment by fanyafeng** [comment]
就是这compose不能和xml一样，能定义一个同名的xml自定义布局就好了

发件人: leavesCZY ***@***.***>
日期: 星期一, 2024年3月11日 18:15
收件人: leavesCZY/Matisse ***@***.***>
抄送: 樊亚风 ***@***.***>, Author ***@***.***>
主题: Re: [leavesCZY/Matisse] 关于自定义媒体列表页顶部和底部View的配置 (Issue #48)

是的。毕竟需要自定义 UI 的属于小众需求，只开放一部分的话意义不大，开放全部又不太现实

―

**Comment by fanyafeng** [comment]
实际修改了下源码，做成配置确实意义不大
