### ISSUE TITLE
默认图片过多时加载会卡顿

### ISSUE THREAD

**Issue by syuhung** [leavesCZY/Matisse#50]
请问能否设定初始文件夹，当前手机内图片过多时在"全部"检索速度会很慢

**Comment by leavesCZY** [comment]
系统相册应该没有所谓的初始文件夹这个概念，这种也许只能根据 bucket 来分别加载图片才能提升加载速度了。另外，debug 包和 release 包的性能差异是比较大的，在 release 包下也需要这么久吗
