### ISSUE TITLE
支持手势滑动选择吗？跟QQ相册或者系统相册一样~

### ISSUE THREAD

**Issue by bsxy000** [leavesCZY/Matisse#52]
如果不支持，可以考虑改造一下^_^

**Comment by leavesCZY** [comment]
不太明白你说的手势滑动选择具体是指啥哟，你要说清楚点~~

**Comment by limingbang** [comment]
应该是说的这个效果吧：https://mp.weixin.qq.com/s/DgCwDk0Sk5LrkvMlSSkw7g

**Comment by bsxy000** [comment]
> 不太明白你说的手势滑动选择具体是指啥哟，你要说清楚点~~

可能是你平时用的少，或者没理解这个意思哈，微信聊天发图其实就可以滑动选择的。^_^
现在滑动选图很常见的，跟楼上那位发的效果类似的，现在不管是Android还是iOS的系统相册在编辑状态下，基本都支持滑动选择，可以用你的手机试试，也可以直接看微信聊天时选图，可以参考下。

**Comment by bsxy000** [comment]
> 应该是说的这个效果吧：https://mp.weixin.qq.com/s/DgCwDk0Sk5LrkvMlSSkw7g

Yes！O(∩_∩)O~

**Comment by leavesCZY** [comment]
soga，我平时还真没注意到可以这么选择图片，我都是直接单击选择的。我记录下这个问题，但不保证后面会这么来实现哈。。。

**Comment by bsxy000** [comment]
> soga，我平时还真没注意到可以这么选择图片，我都是直接单击选择的。我记录下这个问题，但不保证后面会这么来实现哈。。。

恩尼，可以在你的基础上进行改造的，我们调研了一些用户，还是因为微信&QQ和手机相册的使用习惯，想要这种方式的，会很快方便很多的。

Fighting，期待你的更新，酌情考虑安排一下子！(#^.^#)
