### ISSUE TITLE
图片加载很慢，不知道是什么原因。魅族17，性能不算很差。

### ISSUE THREAD

**Issue by lany192** [leavesCZY/Matisse#54]

**Comment by leavesCZY** [comment]
可以先看看这个确认下是否相同情况：https://github.com/leavesCZY/Matisse/issues/50

**Comment by limingbang** [comment]
我的魅族17更新到10.5的版本后，查出来的图片，有很多只展示占位图，其实哪些图片是没有的。Android系统是13
![WechatIMG4](https://github.com/leavesCZY/Matisse/assets/50489504/0a9b2278-5562-4693-b1d9-ed4c4addd647)

**Comment by leavesCZY** [comment]
@limingbang 你们都是在魅族 17 上出问题了啊？？我不确定这是否是系统 bug，还是说是因为系统数据库里存在脏数据导致的，你能否试着打开其它应用的相册列表，看其是否也会这样子

**Comment by limingbang** [comment]
@leavesCZY 我对比其他app的选图，没有这个问题。这个是我自己demo遇到的，过段时间我就有时间了，我可以自己查一查。话说，我升级系统版本后，加载确实变慢了，都比不过魅族m15了，我对比了一个App选图，就是使用了之前老版的matisse（知乎搞的那个），还是很快的

**Comment by leavesCZY** [comment]
嗯啊，如果有排查出是啥问题的话也希望你后续能反馈下，我手头没对应的手机也不好排查问题。至于加载慢的问题，这也是经常被吐槽的问题了，目前 LazyColumn 在性能上的确不如 RecyclerView
