### ISSUE TITLE
在vivo x100手机上使用有bug，给不了相册权限

### ISSUE THREAD

**Issue by LZRight123** [leavesCZY/Matisse#59]
1. 提bug： 在vivo x100手机上使用有bug，给不了相册权限
2.提建议：自定义主题，可以加一个Config 类，传 Color,  用 Compose 然后在xml配置颜色还是有点

**Comment by leavesCZY** [comment]
1、你确定是有声明权限吗？或者说你授予的只是允许访问部分媒体的权限？
2、最早的时候 Matisse 就是这么做的，但 Compose 的 Color 类无法实现 Parcelize，而如果是用自定义类的话我觉得还不如使用 XM

**Comment by LZRight123** [comment]
> 1、你确定是有声明权限吗？或者说你授予的只是允许访问部分媒体的权限？ 2、最早的时候 Matisse 就是这么做的，但 Compose 的 Color 类无法实现 Parcelize，而如果是用自定义类的话我觉得还不如使用 XM
第1个待观察 权限给了 READ_MEDIA_IMAGES
第2个可能因为我上手就是用 compose 不太习惯于 xml .还好
