### ISSUE TITLE
出现过一次崩溃

### ISSUE THREAD

**Issue by iLucasLiu** [leavesCZY/Matisse#60]
---java.lang.IncompatibleClassChangeError: Found interface androidx.compose.ui.graphics.drawscope.DrawScope, but class was expected (declaration of 'androidx.compose.ui.graphics.drawscope.DrawScope'

**Comment by leavesCZY** [comment]
你是不是从旧版本升级到 2.0.0 版本的？然后也没重新根据 wiki 进行修改

**Comment by iLucasLiu** [comment]
是升2.0.0之前的版本报的，还没升到2.0.0，但就看见过这一次。再也没报过了，后续我再观察下。

**Comment by leavesCZY** [comment]
一般崩溃问题都是由于 compose 版本兼容性导致的，但如果是只出现过一次的话我就说不太准了

**Comment by iLucasLiu** [comment]
> 一般崩溃问题都是由于 compose 版本兼容性导致的，但如果是只出现过一次的话我就说不太准了

这个兼容性一般怎么解决，您这边有遇到过么？

**Comment by leavesCZY** [comment]
我自己是没遇到的，因为我自己会控制 compose 版本保证兼容性。你可以看下已经关闭的其它 issues，有好几个说崩溃的，我有对这种情况进行说明
