### ISSUE TITLE
魅族17，仅图片下，查询出来的图片有些是无效的

### ISSUE THREAD

**Issue by limingbang** [leavesCZY/Matisse#61]
1、出问题图片日志
![log](https://github.com/leavesCZY/Matisse/assets/50489504/650bd1a7-30a7-4c77-baae-044aa6deab66)
2、可以修改查询条件修复
![query](https://github.com/leavesCZY/Matisse/assets/50489504/95f1f3ad-857c-4f35-8592-9c197abf61d1)
3、可以更改contentUri来修复
![uri](https://github.com/leavesCZY/Matisse/assets/50489504/198f1be1-4def-48cb-bf26-0e958cb7e70d)

**Comment by leavesCZY** [comment]
十分感谢，后续我验证下在其它机子上是否也能正常运行

**Comment by leavesCZY** [comment]
你好，针对这个问题我已根据你提供的第一种方法进行修改了，但由于我手头没有相应的魅族手机进行验证，不敢就直接发布正式版。能否麻烦你帮忙验证下问题是否已解决呢？方便的话可以下载源代码进行验证，或者是引用我发布在 jitpack 的远程依赖进行验证

`
	dependencyResolutionManagement {
		repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
		repositories {
			mavenCentral()
			maven { url 'https://www.jitpack.io' }
		}
	}

	dependencies {
	        implementation 'com.github.leavesCZY:Matisse:0cbcb41742'
	}
`

**Comment by leavesCZY** [comment]
你好，针对这个问题我已根据你提供的第一种方法进行修改了，但由于我手头没有相应的魅族手机进行验证，不敢就直接发布正式版。能否麻烦你帮忙验证下问题是否已解决呢？方便的话可以下载源代码进行验证，或者是引用我发布在 jitpack 的远程依赖进行验证

```
dependencyResolutionManagement {
        repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
        repositories {
                mavenCentral()
                maven { url 'https://www.jitpack.io' }
        }
}

dependencies {
        implementation 'com.github.leavesCZY:Matisse:0cbcb41742'
}
```

**Comment by limingbang** [comment]
可以。我改下依赖版本验证下

**Comment by limingbang** [comment]
我这里跑完是没问题了

**Comment by leavesCZY** [comment]
收到，谢谢！

**Comment by leavesCZY** [comment]
此问题在 v2.1.0 版本已修复
