### ISSUE TITLE
大佬,有个问题,拍照之后完成之后,没有展示在图片列表,然后再次进才会展示.最新的代码

### ISSUE THREAD

**Issue by lydlovezjr** [leavesCZY/Matisse#66]
如题

**Comment by leavesCZY** [comment]
现在应该是拍完后就直接退出 Matisse 了吧？那自然是看不到啊，还是说拍完后第一次进去时没看到

**Comment by lydlovezjr** [comment]
拍完之后，当前的列表没有

leavesCZY ***@***.***> 于 2024年7月4日周四 11:27写道：

**Comment by lydlovezjr** [comment]
相册选择里边不是有个拍照。拍完照，不在那个列表展示

白店 ***@***.***> 于 2024年7月4日周四 12:42写道：

**Comment by leavesCZY** [comment]
你用的是哪种拍照策略

**Comment by lydlovezjr** [comment]
我用的你的demo,佬.
复现步骤;
1.默认demo是3张,然后拍没问题,会回到首页.
2.然后在首页把maxSelectable改成2,再拍就有问题了

**Comment by lydlovezjr** [comment]
很奇怪这个问题,不是必现的,我给你拍个视频吧,佬,github上能发视频吗

**Comment by lydlovezjr** [comment]
我已经录屏录到这个问题了

**Comment by lydlovezjr** [comment]
加你个QQ还是微信吗,发你视频一看就明白了

**Comment by leavesCZY** [comment]
ok。你发我邮箱我看看：1990724437@qq.com

**Comment by lydlovezjr** [comment]
screen-20240704-141829.mp4
<https://drive.google.com/file/d/1R17eMREp6jlefBC3ihHF6gub9mPYNzM1/view?usp=drive_web>


leavesCZY ***@***.***> 于2024年7月4日周四 15:50写道：

**Comment by lydlovezjr** [comment]
发了,佬,你看看,最后一次拍照就卡住没回到首页

**Comment by leavesCZY** [comment]
你是发到了哪里啊？？邮箱没看到，垃圾箱里也没有。还是说发到了 Google Drive？我也看不到啊。。

**Comment by lydlovezjr** [comment]
https://drive.google.com/file/d/1R17eMREp6jlefBC3ihHF6gub9mPYNzM1/view?usp=drive_web

**Comment by lydlovezjr** [comment]
这个链接有吗,佬

**Comment by leavesCZY** [comment]
访问受限啊。我刚才有点击申请权限了

**Comment by lydlovezjr** [comment]
共享了,佬

**Comment by lydlovezjr** [comment]
可以访问吗,佬

**Comment by leavesCZY** [comment]
看到的了。你这是前面四次拍照都能看到图片，就后面不行了是吗？我猜测是因为当你在拍照页面点击确定按钮的时候，系统还未完全保存好图片导致的，此时 Matisse 根据 Uri 还未能查到对应的图片，所以反应上就和用户 Cancel 了一样。等到你再次进入到图片列表页的时候，图片已经保存好了，所以就又能看到了。如果真是这样的话，系统这种保存时机问题我倒不太确定该如何解决

**Comment by leavesCZY** [comment]
另外，补充一点，你可以试试在拍照页面稍微多停留一点时间，如果这样就不会再出现这种情况的话，那就可以确定是上述原因导致的了

**Comment by lydlovezjr** [comment]
好的,佬
