### ISSUE TITLE
incompatible version of Kotlin

### ISSUE THREAD

**Issue by superoidlau** [leavesCZY/Matisse#68]
`Class 'github.leavesczy.matisse.CoilImageEngine' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.0.0, expected version is 1.8.0....`

编译报错，提示Kotlin版本不兼容，我的Kotlin版本为：1.8.10。

所以编译该库有什么环境要求吗？ 比如Kotlin要满足什么版本？

谢谢。

**Comment by leavesCZY** [comment]
Matisse 最新版本使用的 Kotlin 版本是 2.0.0，看起来是和你的主项目版本差值过大导致不兼容，一般也是需要两端 kotlin 的第一位和第二位版本号一样才能兼容了。Matisse 的 1.0.0 版本就使用的 1.8.10，你可以试试看。但你就需要去看很久以前的 wiki 接入文档了

**Comment by superoidlau** [comment]
> Matisse 最新版本使用的 Kotlin 版本是 2.0.0，看起来是和你的主项目版本差值过大导致不兼容，一般也是需要两端 kotlin 的第一位和第二位版本号一样才能兼容了。Matisse 的 1.0.0 版本就使用的 1.8.10，你可以试试看。但你就需要去看很久以前的 wiki 接入文档了

嗯，谢谢答复，我升级到2.0.0了。

**Comment by superoidlau** [comment]
Close.
升级Kotlin版本到 `2.0.0.`
KSP版本到`2.0.0-1.0.22`
