### ISSUE TITLE
图片预览崩溃

### ISSUE THREAD

**Issue by SamiuZhong** [leavesCZY/Matisse#69]
在选择器界面预览图片即崩溃，我注意到 #10 和 #17 的解决方案,，检查了果然是Compose版本过高导致的Crash。

当我把composeBom版本更改为和Matisse相同的2024.05.00就不会崩溃了。

但是这里又引申出一个问题，有没有办法让我的Compose版本不要和Matisse的Compose版本强制绑定呢？目前这种方式都只能等Matisse发布更新，项目的Compose版本才能够跟随着更新。

**Comment by leavesCZY** [comment]
这种只要 compose 高低版本之间互相不兼容就没法避免了吧。我有看到最近 composeBom 已经到了 09.01 了，但最近实现太忙就没有顾上，你现在就是因为使用的就是 09.01 造成崩溃的吗

**Comment by SamiuZhong** [comment]
是的，就是用的 09.01 版本崩溃

**Comment by leavesCZY** [comment]
目前 v2.1.1 版本也已同步升级到了 09.01，应该可以解决你的问题了
