### ISSUE TITLE
如何应对国内各大app商店的隐私政策

### ISSUE THREAD

**Issue by yanglei9999** [leavesCZY/Matisse#70]
现在国内app商店都需要在申请相机和相册 权限的时候, 弹窗告知用户为什么要申请这个权限
而且不能同时申请 2 个权限, 要一个, 一个申请

<img width="274" alt="image" src="https://github.com/user-attachments/assets/7a445090-2277-4ce4-b47f-20a66a19cc68">

请问, 同时用拍照和图片的时候, 打开图片选择器后, 点击相机图标, 如何能再权限请求之前, 弹出弹窗?

**Comment by leavesCZY** [comment]
目前是没有办法实现你这个需求的，而且也大概率不会来实现，这种事情不应该内置到一个纯粹的媒体资源选择框架里。建议你在外部直接向用户选择“仅拍照”和“仅选择图片”这两个选项，在外部针对性地事先申请好权限后再跳转到 Matisse

**Comment by yanglei9999** [comment]
直接向用户选择“仅拍照”和“仅选择图片”这两个选项  我现在就是这么做的, 但是 失去了最好的用户体验,  必须咱们这个开源项目国内用的还是多的,  可否把一些涉及权限的 **私有**方法变成 可以继承的, 方便扩展, 也不影响 纯粹 性

**Comment by leavesCZY** [comment]
你说的这种方式我想了下，如果真要开放出来的话，势必复杂度会高出很多，性价比实在不高，暂不考虑哈
