### ISSUE TITLE
小米手机打开相册提示“请授予相册访问权限后重试”，具体系统信息如下

### ISSUE THREAD

**Issue by ZHLhenry** [leavesCZY/Matisse#74]
![1d6666b1f4da3e23081f8ae11e2f75d5_origin(1)](https://github.com/user-attachments/assets/0ad7028a-5f3a-4161-80d3-0db095932e15)

**Comment by ZHLhenry** [comment]
![Uploading b43fa958b274b951f2c5572d0be4ac7e_origin(1).jpg…]()

**Comment by ZHLhenry** [comment]
![b43fa958b274b951f2c5572d0be4ac7e_origin(1)](https://github.com/user-attachments/assets/483aed75-abf2-42c4-b995-03a96817456e)

**Comment by ZHLhenry** [comment]
应用权限都是授予了的，吊起相机可以，相册就提示 请授予相册访问权限后重试。

**Comment by ZHLhenry** [comment]
我拉了代码，运行看了下。没问题。我自己找原因把。抱歉，打扰了

**Comment by leavesCZY** [comment]
是因为权限类型配置有误吗？解决了就好

**Comment by ZHLhenry** [comment]
是的，对比了配置文件，少了一个权限
