### ISSUE TITLE
使用Coil 3.0版本作为图片加载框架，Matisse直接崩溃

### ISSUE THREAD

**Issue by SamiuZhong** [leavesCZY/Matisse#75]
我使用的是Coil 3.0.3版本作为图片框架，Matisse版本为2.1.2，指定CoilImageEngine。打开选择图片直接崩溃，以下是部分信息。
![c00688a6-0cec-45e2-bbcf-5b084b9dccfc](https://github.com/user-attachments/assets/49fd9f3b-d130-4834-ab2b-a7aa3c751bfb)
![image](https://github.com/user-attachments/assets/3680bc6e-78b4-452c-811b-befd588c5e0a)
![image](https://github.com/user-attachments/assets/89b512cb-ab9e-45b4-af29-7a8a2a49f034)

**Comment by leavesCZY** [comment]
这个是正常的，Coil 3.x 版本和之前的并不兼容，Matisse 的 release 版本暂时没有提供 Coil 3 版本的 ImageEngine，但最新版本里有，你可以参照着自己来实现：https://github.com/leavesCZY/Matisse/blob/master/matisse/src/main/java/github/leavesczy/matisse/ImageEngine.kt
