### ISSUE TITLE
为什么Gradle 各个版本都引入失败 作者能检查一下吗

### ISSUE THREAD

**Issue by LeoSona-coder** [leavesCZY/Matisse#8]
为什么Gradle 各个版本都引入失败 作者能检查一下吗

**Comment by leavesCZY** [comment]
@LeoSona-coder 你确定有引入``

**Comment by leavesCZY** [comment]
@LeoSona-coder 
你确定有声明 jitpack 吗

`
allprojects {

    repositories {

        maven { url "https://jitpack.io" }

    }
    
}
`

**Comment by LeoSona-coder** [comment]
是的 在jitpack 上查询 也是库也是有问题的

**Comment by LeoSona-coder** [comment]
现在好像恢复了 前几天查询 都是有问题的 Log 也为空

**Comment by leavesCZY** [comment]
@LeoSona-coder 也许是 jitpack 服务器挂了吧，偶尔就会这样
