### ISSUE TITLE
打开预览图片之后，没有按钮可以完成选择，也没有按钮返回上一页，只能点击后退按钮/手势返回

### ISSUE THREAD

**Issue by asnhkl1** [leavesCZY/Matisse#9]
如题，这种操作并不是很友好

**Comment by leavesCZY** [comment]
@asnhkl1 返回按钮我倒是觉得没有必要，有点多余。完成选择的按钮可以后续加上

**Comment by leavesCZY** [comment]
@asnhkl1 你说的体验问题我也比较认同，我发布了个新版本 v0.0.10，你看下是否满足你的需求
